[package]
name = "powerscan"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
iced = "0.13.1"
iced_aw = { version = "0.12.2", features = ["menu", "quad"] }
iced_fonts = "0.2.1"
log = "0.4.27"
sane = { path = "../sane/" }
