[package]
name = "powerscan"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
env_logger = "0.11.8"
log = "0.4.27"
relm4 = "0.10.0"
relm4-components = "0.10.0"
sane = { path = "../sane/" }
tokio = { version = "1.47.1", features = ["full"] }
